// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW2VlLWNlkrc-XJ19SSvcedbXcaWvc7GM',
    appId: '1:579015164902:web:9851f38b30870ed5e78c27',
    messagingSenderId: '579015164902',
    projectId: 'fir-face-recognize',
    authDomain: 'fir-face-recognize.firebaseapp.com',
    storageBucket: 'fir-face-recognize.appspot.com',
    measurementId: 'G-P5KX3CZ22L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBjbrxf1SEbGaiFoXFU5o0ReIKMxmTEgM',
    appId: '1:579015164902:android:8345d1c544a65dd5e78c27',
    messagingSenderId: '579015164902',
    projectId: 'fir-face-recognize',
    storageBucket: 'fir-face-recognize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPpdTSexHPF65GwAt4LgoL_n_3KRO0-Ks',
    appId: '1:579015164902:ios:c1b4c1fe9df7d338e78c27',
    messagingSenderId: '579015164902',
    projectId: 'fir-face-recognize',
    storageBucket: 'fir-face-recognize.appspot.com',
    iosClientId: '579015164902-2hio4fnaiuflso4da63k7tkskpsvensg.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceRecognizeDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPpdTSexHPF65GwAt4LgoL_n_3KRO0-Ks',
    appId: '1:579015164902:ios:c1b4c1fe9df7d338e78c27',
    messagingSenderId: '579015164902',
    projectId: 'fir-face-recognize',
    storageBucket: 'fir-face-recognize.appspot.com',
    iosClientId: '579015164902-2hio4fnaiuflso4da63k7tkskpsvensg.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceRecognizeDemo',
  );
}
